services:
  catalog.api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - ConnectionStrings__Database=Server=localhost;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres
    depends_on:
    image: catalog.api
    build:
     context: .
     dockerfile: Services/Catalog/Catalog.API/Dockerfile

  catalogdb:
    image: postgres
    container_name: catalogDb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - catalog-db:/var/lib/postgresql/data

  basketdb:
    image: postgres
    container_name: basketgDb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: BasketDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - basket-db:/var/lib/postgresql/data 

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
        - "6379:6379"
volumes:
  catalog-db:
