services:
#  catalog.api:
#    image: catalog.api
#    build:
#      context: .
#      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      
  catalog.db:
    image: postgres
    container_name: catalogDb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - catalog-db:/var/lib/postgresql/data

volumes:
  catalog-db:

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Basket/Basket.API/Dockerfile
